/* tslint:disable */
import './bug'
import './component'
import './exit-fullscreen'
import './fold'
import './fullscreen'
import './language'
import './search'
import './setting'
import './side-menu-dark'
import './side-menu-light'
import './size'
import './tick'
